### ISSUE TITLE
Trackback Error

### ISSUE THREAD

**Issue by timo1302** [maikka39/WatchTogether#1]
Hello,

when i run the command `python main.py`, i get a output (error). Here the output:

`Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from html import escape
ImportError: No module named html`

How i can fix this error?

Best regards
TwodoHD

**Comment by TwodoHD** [comment]
eventlet, python-socketio, flask are already installed on the server.

**Comment by maikka39** [comment]
Hi, just do this:
```python
pip3 install html
```

I've also updated the dependencies.

**Comment by TwodoHD** [comment]
Hello maikka93,

thank you for your answere. I have fixed this error.

Have a nice day.

Best regards
TwodoHD
