### ISSUE TITLE
No content on hosted site

### ISSUE THREAD

**Issue by dly2424** [maikka39/WatchTogether#4]
When connecting to http://x.x.x.x:8080 it connects, i see it connect in the output, i get a blank page with a green bar at the top. Is there some sort of configuration required?

Using Python3.4, but tried other versions as well. Dependencies are met.

**Comment by maikka39** [comment]
Hi,

I haven't worked on this project for a while and it is far from done so my excuse for that.
I'm planning to continue with this project once my exams are over.

But, on your issue:
If you go to http://x.x.x.x:8080/room/test it should load the room. (You can replace "test" with any text you want)

Hope this helped
